---
title: "crimeagimg"
author: "Sophia Freuden"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(fs)
library(scales)
library(tidyverse)
```

### R Markdown for Crime in 2018 by Victim Type  

<br>

#### These plots are rendered as images and saved to a directory within my app that then renders them in Shiny.  

<br>

*Please see the readme file for specific instructions on how to run these codes chunks (i.e. what order to run them in).*  

```{r reading in 2015 crime file}
# I determined early on what columns would need to be cast for my
# crime data files for 2015 to 2019. I used the same casting for
# all five of these files. I had issues with the 2016 file, though,
# because it was missing a longitude column. I contacted the
# Portland Police Bureau, however, and they fixed it, which was
# pretty cool.

a <- read_csv(file = "cleaned-data/CrimeData-2015.csv", col_types = cols(
  Address = col_character(),
  CaseNumber = col_character(),
  CrimeAgainst = col_character(),
  Neighborhood = col_character(),
  OccurDate = col_character(),
  OccurTime = col_character(),
  OffenseCategory = col_character(),
  OffenseType = col_character(),
  OpenDataLat = col_double(),
  OpenDataLon = col_double(),
  OpenDataX = col_character(),
  OpenDataY = col_character(),
  ReportDate = col_character(),
  OffenseCount = col_double()
))
```

```{r 2015 crime against plot and image, include=FALSE}
# I originally had all of the code in this Rmd in an R script file
# that I had been using to build my project. Because of issues I
# was having with my images printing in Shiny properly, I decided
# to switch how I was saving my plots as images based off of a
# recommendation Bernadette gave me.

crimeag15 <- ggplot(a, aes(x = CrimeAgainst, fill = CrimeAgainst)) +
  geom_bar(show.legend = FALSE) +
  labs(title = "Distribution of Crimes per Victim Type in 2015") +
  xlab("Type of Victim") +
  ylab("Count") +
  theme(legend.position = "none") +
  theme_minimal()

# Prior to this, I had been using ggsave in a similar way. Bernadette
# said she found the method below online because she was having similar
# issues with getting her images to load properly. Because this method
# doesn't employ pipes, having it split into "runnable" code chunks
# in an Rmd made more sense than leaving it in its origianl R script.

png("crimeag15.png", width = 576, height = 576, res = 120)
crimeag15
dev.off()

# Don't forget to load fs for file_copy!

file_copy(
  path = "crimeag15.png",
  new_path = "pdx-probs/www/crimeag15.png",
  overwrite = TRUE
)

file_delete(path = "crimeag15.png")
```

```{r 2016 crime against plot and image, include=FALSE}
b <- read_csv(file = "cleaned-data/CrimeData-2016.csv", col_types = cols(
  Address = col_character(),
  CaseNumber = col_character(),
  CrimeAgainst = col_character(),
  Neighborhood = col_character(),
  OccurDate = col_character(),
  OccurTime = col_character(),
  OffenseCategory = col_character(),
  OffenseType = col_character(),
  OpenDataLat = col_double(),
  OpenDataLon = col_double(),
  OpenDataX = col_character(),
  OpenDataY = col_character(),
  ReportDate = col_character(),
  OffenseCount = col_double()
))

# Because these code chunks involved a lot of copying and pasting,
# I had to be very careful to change all the necessary parts.
# I found it helpful to open the image files these code chunks
# produced outside R (in Previewer, for example) to make sure
# everything was rendering properly.

crimeag16 <- ggplot(b, aes(x = CrimeAgainst, fill = CrimeAgainst)) +
  geom_bar(show.legend = FALSE) +
  labs(title = "Distribution of Crimes per Victim Type in 2016") +
  xlab("Type of Victim") +
  ylab("Count") +
  theme(legend.position = "none") +
  theme_minimal()

png("crimeag16.png", width = 576, height = 576, res = 120)
crimeag16
dev.off()

# I had to mess around with the resolution and size of the images
# being saved to get something that wasn't too big in Shiny, but
# also of high enough quality. These numbers--576 and 120--are
# proportional, as 480 is the default for size and 100 is the
# default for resolution. So 1.2 times 480 is 576.

file_copy(
  path = "crimeag16.png",
  new_path = "pdx-probs/www/crimeag16.png",
  overwrite = TRUE
)

file_delete(path = "crimeag16.png")
```

```{r 2017 crime against plot and image, include=FALSE}
c <- read_csv(file = "cleaned-data/CrimeData-2017.csv", col_types = cols(
  Address = col_character(),
  CaseNumber = col_character(),
  CrimeAgainst = col_character(),
  Neighborhood = col_character(),
  OccurDate = col_character(),
  OccurTime = col_character(),
  OffenseCategory = col_character(),
  OffenseType = col_character(),
  OpenDataLat = col_double(),
  OpenDataLon = col_double(),
  OpenDataX = col_character(),
  OpenDataY = col_character(),
  ReportDate = col_character(),
  OffenseCount = col_double()
))

crimeag17 <- ggplot(c, aes(x = CrimeAgainst, fill = CrimeAgainst)) +
  geom_bar(show.legend = FALSE) +
  labs(title = "Distribution of Crimes per Victim Type in 2017") +
  xlab("Type of Victim") +
  ylab("Count") +
  theme(legend.position = "none") +
  theme_minimal()

# It also took a bit of messing around in Shiny to get these
# images to center properly. That code is in the app, however,
# and uses something I found online.

png("crimeag17.png", width = 576, height = 576, res = 120)
crimeag17
dev.off()

file_copy(
  path = "crimeag17.png",
  new_path = "pdx-probs/www/crimeag17.png",
  overwrite = TRUE
)

file_delete(path = "crimeag17.png")
```

```{r 2018 crime against plot and image, include=FALSE}
d <- read_csv(file = "cleaned-data/CrimeData-2018.csv", col_types = cols(
  Address = col_character(),
  CaseNumber = col_character(),
  CrimeAgainst = col_character(),
  Neighborhood = col_character(),
  OccurDate = col_character(),
  OccurTime = col_character(),
  OffenseCategory = col_character(),
  OffenseType = col_character(),
  OpenDataLat = col_double(),
  OpenDataLon = col_double(),
  OpenDataX = col_character(),
  OpenDataY = col_character(),
  ReportDate = col_character(),
  OffenseCount = col_double()
))

crimeag18 <- ggplot(d, aes(x = CrimeAgainst, fill = CrimeAgainst)) +
  geom_bar(show.legend = FALSE) +
  labs(title = "Distribution of Crimes per Victim Type in 2018") +
  xlab("Type of Victim") +
  ylab("Count") +
  theme(legend.position = "none") +
  theme_minimal()

# Lots of copying and pasting!

png("crimeag18.png", width = 576, height = 576, res = 120)
crimeag18
dev.off()

file_copy(
  path = "crimeag18.png",
  new_path = "pdx-probs/www/crimeag18.png",
  overwrite = TRUE
)

file_delete(path = "crimeag18.png")
```

```{r 2018 crime against plot and image, include=FALSE}

# Don't forget your code chunk titles!

e <- read_csv(file = "cleaned-data/CrimeData-2019.csv", col_types = cols(
  Address = col_character(),
  CaseNumber = col_character(),
  CrimeAgainst = col_character(),
  Neighborhood = col_character(),
  OccurDate = col_character(),
  OccurTime = col_character(),
  OffenseCategory = col_character(),
  OffenseType = col_character(),
  OpenDataLat = col_double(),
  OpenDataLon = col_double(),
  OpenDataX = col_character(),
  OpenDataY = col_character(),
  ReportDate = col_character(),
  OffenseCount = col_double()
))

# I had to come back and hide all the legends in all the bar
# charts in the Rmd.

crimeag19 <- ggplot(e, aes(x = CrimeAgainst, fill = CrimeAgainst)) +
  geom_bar(show.legend = FALSE) +
  labs(
    title = "Distribution of Crimes per Victim Type in 2019",
    subtitle = "Year to Date (January through September)"
  ) +
  xlab("Type of Victim") +
  ylab("Count") +
  theme(legend.position = "none") +
  theme_minimal()

png("crimeag19.png", width = 576, height = 576, res = 120)
crimeag19
dev.off()

# While it makes me nervous to keep the overwrite set to TRUE,
# it makes it easier, because then it rewrites the image every
# time I need to make a change to the plot. The trick is to
# remember to change it in ggplot and also rerun the saving
# and file copy functions.

file_copy(
  path = "crimeag19.png",
  new_path = "pdx-probs/www/crimeag19.png",
  overwrite = TRUE
)

# Leave no trails. I added this file_delete to all the chunks in this Rmd to get rid of the unnecessary pngs I created in the process of creating these images.

file_delete(path = "crimeag19.png")
```

```{r}
crimeag15
crimeag16
crimeag17
crimeag18
crimeag19
```

