---
title: "crratetime"
author: "Sophia Freuden"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(fs)
library(readxl)
library(tidyverse)
```

### R Markdown for Differing Crime Rates Plotted Over Time and Precitions  

<br>

#### These plots are rendered as images and saved to a directory within my app that then renders them in Shiny.  

<br>

*Please see the readme file for specific instructions on how to run these codes chunks (i.e. what order to run them in).*  

```{r reading in crime rate and population data}
custom <- read_xlsx(path = "cleaned-data/Crime Rate + Pop.xlsx")

# This reads in the data table that I made from hand by copying
# the data from the PDF I found from the PPB. This data also
# contains a population column from the U.S. Census that I copied
# from a separate csv file that I got. You could hypoethetically
# do a join to produced the same data tibble here in R, but
# because I was already in the process of creating the Excel
# file, I decided this was easiest. I also make a note of this in
# my readme file.
```

```{r plotting property crime rate over time}
# I knew roughly what I wanted this graph to look like before I
# made it. I wanted it to be a line graph (which generally make
# the most sense for single data plots per x axis point, so year
# in this case). From there, I just needed to add labels and such
# based of what I saw in the original plot. I also added a
# minimal theme. I used minimal themes in all of my graphs for
# my app.

propplot <- ggplot(custom, aes(x = Year, y = PropertyCrimeRt)) +
  geom_line() +
  labs(
    title = "Property Crime Rate Over Time",
    subtitle = "Seemingly Sharp Increase in Population Over Time",
    caption = "The rate is number of crimes per 1,000 people."
  ) +
  ylab("Property Crime Rate") +
  theme_minimal() +
  geom_smooth(method = "lm", se = FALSE)

# Note to self: keep the lm here per Georgie's general feedback
# on when to use lm lines or not.
```

```{r saving the propery crime rate plot as an image, include=FALSE}
# I'm not sure if these Rmd files need to knit nicely as
# a part of this assignment. I tried knitting one and it
# worked, but I was getting weird messages in the knit
# as a result of my image-saving code. I set include=FALSE
# in all code chunks in all Rmd files that had this image
# saving code. I also created a redunant code chunk at the
# end that has the plots of each of the files in them
# so that the visual would show up in a knit.

# This uses the same methods that I explain in detail in my
# crimeagimg Rmd. The first chunk produces and saves the image
# and the second one copies it into my app. The third deletes
# the intermediate version of it that is produced in the
# working directory.

png("propplot.png", width = 576, height = 576, res = 120)
propplot
dev.off()

file_copy(
  path = "propplot.png",
  new_path = "pdx-probs/www/propplot.png",
  overwrite = TRUE
)

file_delete(path = "propplot.png")

# Don't forget the little things, like the ".png" above!

# If you are worried about whether this method works,
# definitely test it out and ensure that the images are
# rendering how they should be and are being saved in the
# right places and then deleted from the working directory.
```

```{r plotting the person crime rate over time, include=FALSE}
# This is the same thing as above, but this plots the person
# crime rate instead of the property crime rate.

persplot <- ggplot(custom, aes(x = Year, y = PersonCrmRt)) +
  geom_line() +
  labs(
    title = "Person Crime Rate Over Time",
    subtitle = "Slight Increase Over Time",
    caption = "The rate is number of crimes per 1,000 people."
  ) +
  ylab("Person Crime Rate") +
  theme_minimal()

# This plot does not have an lm fit to it.

png("persplot.png", width = 576, height = 576, res = 120)
persplot
dev.off()

file_copy(
  path = "persplot.png",
  new_path = "pdx-probs/www/persplot.png",
  overwrite = TRUE
)

file_delete(path = "persplot.png")
```

```{r creating a tibble for predictions for 2019 through 2023}
# While this is fairly simple and straightforward, I had
# never done anything like this before. I initially looked
# for an R function that would automatically add predicted
# vales to a plot and then continue the line from there.
# I couldn't find exactly what I wanted, so I decided
# to make my own tibbles.

future <- tibble(Year = c(2019, 2020, 2021, 2022, 2023))

# First I made a simple tibble that would get fed into
# my lm function to predict those population values
# for those years.

model <- lm(PropertyCrimeRt ~ Year, data = custom)

# Then I constructed the necessary lm function to feed
# into the predict() function in R.

rows <- tibble(
  PropertyCrimeRt = predict(model, newdata = future),
  Year = c(2019, 2020, 2021, 2022, 2023)
)

# Then I made another tibble that combines my lm data
# and the year values.

proponly <- custom %>%
  select(PropertyCrimeRt, Year)

# I made things simple by identifying the columns I wanted.
# This is unnecessary, but it makes life easier. I didn't
# want a ton on NA values for the columns in my Excel
# file that are irrelevant to my prediction model.

proppred <- proponly %>% bind_rows(rows)

# Bernadette told me about the bind_rows() function, which
# is kind of like joining data, but by rows istead of columns.
# I played around with test data to make sure all of this worked,
# none of which I included here... but I do recommend testing
# things before putting them in Shiny.
```

```{r plotting my property crime rate prediction}
# This was straightforward. All I needed was the data that
# had the binded rows.

proppredplot <- ggplot(proppred, aes(x = Year, y = PropertyCrimeRt)) +
  geom_line() +
  labs(
    title = "Predicted Property Crime Rate Over Time",
    subtitle = "2019 through 2023 Predicted",
    caption = "The rate is number of crimes per 1,000 people.
       Vertical line denotes start of predicted data."
  ) +
  ylab("Property Crime Rate") +
  theme_minimal() +
  geom_vline(xintercept = 2019, color = "blue") +
  scale_x_continuous(breaks = c(
    2011,
    2013,
    2015,
    2017,
    2019,
    2021,
    2023
  ))
# I added some aesthetic elements here, inlcuding a blue line
# so you can where my predicted data begins.

# The original plot had a weird default setting for which years
# it displayed on the x acis. I used scale_x_continous here
# to dictate which years I thought it should display.
```

```{r saving the plot of my predicted values for 2019 through 2023, include=FALSE}
png("proppredplot.png", width = 576, height = 576, res = 120)
proppredplot
dev.off()

file_copy(
  path = "proppredplot.png",
  new_path = "pdx-probs/www/proppredplot.png",
  overwrite = TRUE
)

file_delete(path = "proppredplot.png")

# If your images aren't displaying the right image, make sure
# you rerun the code chunk with the corresponding ggplot function.

# Note to self: any further changes made to these plots should
# be made in this rmd and not the original R script file.
```

```{r}
propplot
persplot
proppredplot
```

