---
title: "monthspread"
author: "Sophia Freuden"
date: "11/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(fs)
library(scales)
library(lubridate)
library(tidyverse)
```

### R Markdown for Differing Crime Rates Plotted Over Time and Precitions  

<br>

#### These plots are rendered as images and saved to a directory within my app that then renders them in Shiny.  

<br>

*Please see the readme file for specific instructions on how to run these codes chunks (i.e. what order to run them in).*  

```{r reading in data for 2015 crime}
# I do more or less the same thing across multiple Rmd files,
# but I call the data something different every time. I'm not
# entirely should how the environment in R Studio works for
# saved objects. I don't know if you save data as an object
# in R for use in one Rmd that you will be able to call the
# same object in another Rmd. I always read them into new
# objects and name them something different.

months15 <- read_csv(file = "cleaned-data/CrimeData-2015.csv", col_types = cols(
  Address = col_character(),
  CaseNumber = col_character(),
  CrimeAgainst = col_character(),
  Neighborhood = col_character(),
  OccurDate = col_character(),
  OccurTime = col_character(),
  OffenseCategory = col_character(),
  OffenseType = col_character(),
  OpenDataLat = col_double(),
  OpenDataLon = col_double(),
  OpenDataX = col_character(),
  OpenDataY = col_character(),
  ReportDate = col_character(),
  OffenseCount = col_double()
))
```

```{r modifying the date columns with lubridate}
# Lubridate is a helpful package that we have been
# using as a class for a while now. It can be hard
# to use at first, but if you google "lubridate
# cheat sheet", the first thing that comes up is
# a PDF that is incredibly helpful.

months15 <- months15 %>%
  mutate(OccurDate = mdy(OccurDate)) %>%
  mutate(ReportDate = mdy(ReportDate))

# Here I modify the columns for both the Occur Date
# and Report Date, even though I only work with Occur
# Date moving forward. I did this for consistency's
# sake, though this is somewhat unnecessary.

months15 <- months15 %>%
  mutate(OccurYear = year(OccurDate)) %>%
  mutate(OccurMonth = month(OccurDate))
```

```{r creating plot data for 2015 crime grouped by month}
# You should note that the crime data file for 2015
# contains crimes that were reported in 2015, but
# didn't actually occur that year. Here I filter
# for only cases in which crime occured in 2015.

monthspread15 <- months15 %>%
  filter(OccurYear == 2015) %>%
  group_by(OccurMonth) %>%
  count()

# I group by month and count them so that I can plot
# them below.
```

```{r plotting 2015 crime count by month}
plotmonths15 <- ggplot(monthspread15, aes(x = OccurMonth, y = n)) +
  geom_line() +
  theme_minimal() +
  labs(
    title = "Number of Total Crimes Over Months in 2015",
    subtitle = "Significantly lower numbers in early months"
  ) +
  xlab("Month") +
  ylab("Number of Crimes Reported") +
  scale_y_continuous(limits = c(0, NA), labels = comma) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))

# To get commas in the y axis labels, load the scales
# package and put labels = comma in scale_y_continuous.
# It's magic.

# Note to self: do not keep lm line in these plots.
```

```{r saving the plot of 2015 crime count by month, include=FALSE}
# I'm not sure if these Rmd files need to knit nicely as
# a part of this assignment. I tried knitting one and it
# worked, but I was getting weird messages in the knit
# as a result of my image-saving code. I set include=FALSE
# in all code chunks in all Rmd files that had this image
# saving code. I also created a redunant code chunk at the
# end that has the plots of each of the files in them
# so that the visual would show up in a knit.

# The image seemed a little smooshed together after I
# checked it out in Previewer, so I altered the width
# here to be 606 instead of my standard 576.

png("plotmonths15.png", width = 606, height = 576, res = 120)
plotmonths15
dev.off()

file_copy(
  path = "plotmonths15.png",
  new_path = "pdx-probs/www/plotmonths15.png",
  overwrite = TRUE
)

file_delete(path = "plotmonths15.png")
```

```{r 2016 monthly crime count plot and image, include=FALSE}
# The rest of this file is just a lot of copying and pasting
# the basic structure I've laid out above, but adjusting
# for which year (and therefore data file) you are looking
# at.

months16 <- read_csv(file = "cleaned-data/CrimeData-2016.csv", col_types = cols(
  Address = col_character(),
  CaseNumber = col_character(),
  CrimeAgainst = col_character(),
  Neighborhood = col_character(),
  OccurDate = col_character(),
  OccurTime = col_character(),
  OffenseCategory = col_character(),
  OffenseType = col_character(),
  OpenDataLat = col_double(),
  OpenDataLon = col_double(),
  OpenDataX = col_character(),
  OpenDataY = col_character(),
  ReportDate = col_character(),
  OffenseCount = col_double()
))

months16 <- months16 %>%
  mutate(OccurDate = mdy(OccurDate)) %>%
  mutate(ReportDate = mdy(ReportDate))

months16 <- months16 %>%
  mutate(OccurYear = year(OccurDate)) %>%
  mutate(OccurMonth = month(OccurDate))

monthspread16 <- months16 %>%
  filter(OccurYear == 2016) %>%
  group_by(OccurMonth) %>%
  count()

plotmonths16 <- ggplot(monthspread16, aes(x = OccurMonth, y = n)) +
  geom_line() +
  theme_minimal() +
  labs(
    title = "Number of Total Crimes Over Months in 2016",
    subtitle = "General increase over time with significant dropoff in December",
    caption = "2016 graph scaled on y axis to show dynamism."
  ) +
  xlab("Month") +
  ylab("Number of Crimes Reported") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))

png("plotmonths16.png", width = 606, height = 576, res = 120)
plotmonths16
dev.off()

file_copy(
  path = "plotmonths16.png",
  new_path = "pdx-probs/www/plotmonths16.png",
  overwrite = TRUE
)

file_delete(path = "plotmonths16.png")

# I recommend running each of these chunks at a time to make
# sure the images are rendering properly. My code chunks
# are a bit large here because I am just copying and pasting
# from an R script file that had all of this code in it
# originally. Because I tested it a lot there, I know it works
# here (plus my images are rendering properly).

# If you are having issues with these large code chunks, try
# breaking them up into smaller pieces to see where the errors
# are originating from.
```

```{r 2017 monthly crime count plot and image, include=FALSE}
months17 <- read_csv(file = "cleaned-data/CrimeData-2017.csv", col_types = cols(
  Address = col_character(),
  CaseNumber = col_character(),
  CrimeAgainst = col_character(),
  Neighborhood = col_character(),
  OccurDate = col_character(),
  OccurTime = col_character(),
  OffenseCategory = col_character(),
  OffenseType = col_character(),
  OpenDataLat = col_double(),
  OpenDataLon = col_double(),
  OpenDataX = col_character(),
  OpenDataY = col_character(),
  ReportDate = col_character(),
  OffenseCount = col_double()
))

months17 <- months17 %>%
  mutate(OccurDate = mdy(OccurDate)) %>%
  mutate(ReportDate = mdy(ReportDate))

months17 <- months17 %>%
  mutate(OccurYear = year(OccurDate)) %>%
  mutate(OccurMonth = month(OccurDate))

monthspread17 <- months17 %>%
  filter(OccurYear == 2017) %>%
  group_by(OccurMonth) %>%
  count()

plotmonths17 <- ggplot(monthspread17, aes(x = OccurMonth, y = n)) +
  geom_line() +
  theme_minimal() +
  labs(
    title = "Number of Total Crimes Over Months in 2017",
    subtitle = "January and December show lulls in reported crime.",
    caption = "2017 graph scaled on y axis to show dynamism."
  ) +
  xlab("Month") +
  ylab("Number of Crimes Reported") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))

png("plotmonths17.png", width = 606, height = 576, res = 120)
plotmonths17
dev.off()

file_copy(
  path = "plotmonths17.png",
  new_path = "pdx-probs/www/plotmonths17.png",
  overwrite = TRUE
)

file_delete(path = "plotmonths17.png")
```

```{r 2018 monthly crime count plot and image, include=FALSE}
months18 <- read_csv(file = "cleaned-data/CrimeData-2018.csv", col_types = cols(
  Address = col_character(),
  CaseNumber = col_character(),
  CrimeAgainst = col_character(),
  Neighborhood = col_character(),
  OccurDate = col_character(),
  OccurTime = col_character(),
  OffenseCategory = col_character(),
  OffenseType = col_character(),
  OpenDataLat = col_double(),
  OpenDataLon = col_double(),
  OpenDataX = col_character(),
  OpenDataY = col_character(),
  ReportDate = col_character(),
  OffenseCount = col_double()
))

months18 <- months18 %>%
  mutate(OccurDate = mdy(OccurDate)) %>%
  mutate(ReportDate = mdy(ReportDate))

months18 <- months18 %>%
  mutate(OccurYear = year(OccurDate)) %>%
  mutate(OccurMonth = month(OccurDate))

monthspread18 <- months18 %>%
  filter(OccurYear == 2018) %>%
  group_by(OccurMonth) %>%
  count()

plotmonths18 <- ggplot(monthspread18, aes(x = OccurMonth, y = n)) +
  geom_line() +
  theme_minimal() +
  labs(
    title = "Number of Total Crimes Over Months in 2018",
    subtitle = "Feburary and December show lulls in reported crime.",
    caption = "2018 graph scaled on y axis to show dynamism."
  ) +
  xlab("Month") +
  ylab("Number of Crimes Reported") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))

png("plotmonths18.png", width = 606, height = 576, res = 120)
plotmonths18
dev.off()

file_copy(
  path = "plotmonths18.png",
  new_path = "pdx-probs/www/plotmonths18.png",
  overwrite = TRUE
)

file_delete(path = "plotmonths18.png")
```

```{r 2019 monthly crime count plot and image, include=FALSE}
months19 <- read_csv(file = "cleaned-data/CrimeData-2019.csv", col_types = cols(
  Address = col_character(),
  CaseNumber = col_character(),
  CrimeAgainst = col_character(),
  Neighborhood = col_character(),
  OccurDate = col_character(),
  OccurTime = col_character(),
  OffenseCategory = col_character(),
  OffenseType = col_character(),
  OpenDataLat = col_double(),
  OpenDataLon = col_double(),
  OpenDataX = col_character(),
  OpenDataY = col_character(),
  ReportDate = col_character(),
  OffenseCount = col_double()
))

months19 <- months19 %>%
  mutate(OccurDate = mdy(OccurDate)) %>%
  mutate(ReportDate = mdy(ReportDate))

months19 <- months19 %>%
  mutate(OccurYear = year(OccurDate)) %>%
  mutate(OccurMonth = month(OccurDate))

monthspread19 <- months19 %>%
  filter(OccurYear == 2019) %>%
  group_by(OccurMonth) %>%
  count()

plotmonths19 <- ggplot(monthspread19, aes(x = OccurMonth, y = n)) +
  geom_line() +
  theme_minimal() +
  labs(
    title = "Number of Total Crimes Over Months in Jan.
    through Sept. 2019",
    subtitle = "Feburary and September show lulls in reported crime.",
    caption = "2019 graph scaled on y axis to show dynamism.
       This data is pulled from a file that includes only year-to-date data for 2019.
       September lull may be attributed to year-to-date nature of data."
  ) +
  xlab("Month") +
  ylab("Number of Crimes Reported") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))

png("plotmonths19.png", width = 576, height = 576, res = 120)
plotmonths19
dev.off()

# On second thought, changing the width above doesn't seem to do much
# of anything.

file_copy(
  path = "plotmonths19.png",
  new_path = "pdx-probs/www/plotmonths19.png",
  overwrite = TRUE
)

file_delete(path = "plotmonths19.png")
```

```{r}
# I include these plots here for the knit, but they don't correspond
# to anything in Shiny.

plotmonths15
plotmonths16
plotmonths17
plotmonths18
plotmonths19
```

