---
title: "unemp"
author: "Sophia Freuden"
date: "11/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(fs)
library(scales)
library(readxl)
library(broom)
library(gt)
library(webshot)
library(tidyverse)
```

### R Markdown for Unemployment Plots and Regressions with Crime Rates

<br>

#### These plots are rendered as images and saved to a directory within my app that then renders them in Shiny.  

<br>

*Please see the readme file for specific instructions on how to run these codes chunks (i.e. what order to run them in).*  

<br>

```{r reading in unemployment data}
# I do more or less the same thing across multiple Rmd files,
# but I call the data something different every time. I'm not
# entirely should how the environment in R Studio works for
# saved objects. I don't know if you save data as an object
# in R for use in one Rmd that you will be able to call the
# same object in another Rmd (I'm pretty sure you can't).
# I always read them into new objects and name them something
# different.

unemp <- read_xlsx(path = "cleaned-data/BLS PDX Unemployment.xlsx")
```

```{r adding yearly average unemployment rate column}
# I originally added this in Excel by hand, but I decided that
# mutating a new column in R would be both cooler and perhaps
# more ethical... plus it spares me from having to explain
# what I did in the readme.

unemp$Avg <- rowMeans(unemp[, 2:13], na.rm = TRUE)

# This took me a little bit to figure out. Averaging across
# rows does not work like using mean() in mutate, because
# that applies a function down a column. Knowing a bit of
# base R is helpful at times! I had to include na.rm =
# TRUE because I don't have data points for 3 months in
# 2019.

# With digits = 1 below, I rounded this average to match
# the rounding of the original data.

unemp <- unemp %>% mutate(Avg = round(Avg, digits = 1))
```

```{r plotting yearly average unemployment rate over time}
unempplot <- ggplot(unemp, aes(x = Year, y = Avg)) +
  geom_line() +
  labs(
    title = "Unemployment Rate of Portland Metropolitan Area
    Over Time",

    # I've had to break titles like this in a couple of my graphs
    # otherwise they get cut off in the images that render.

    subtitle = "Post-recession era sees plummet in unemployment rate"
  ) +
  theme_minimal() +
  scale_x_continuous(breaks = c(2010, 2012, 2014, 2016, 2018)) +
  ylab("Yearly Average Unemployment Rate")

# Forgive my political posturing, I couldn't help it.
```

```{r saving unemployment plot as an image, include=FALSE}
# I'm not sure if these Rmd files need to knit nicely as
# a part of this assignment. I tried knitting one and it
# worked, but I was getting weird messages in the knit
# as a result of my image-saving code. I set include=FALSE
# in all code chunks in all Rmd files that had this image
# saving code. I also created a redunant code chunk at the
# end that has the plots of each of the files in them
# so that the visual would show up in a knit.

png("unempplot.png", width = 576, height = 576, res = 120)
unempplot
dev.off()

file_copy(
  path = "unempplot.png",
  new_path = "pdx-probs/www/unempplot.png",
  overwrite = TRUE
)

file_delete(path = "unempplot.png")

# Make sure all the file names include .png at the end!
```

```{r reading in crime rate and population data}
# This reads in the data table I made by hand using data
# from the Portland Police Bureau and the U.S. Census.

custom2 <- read_xlsx(path = "cleaned-data/Crime Rate + Pop.xlsx")
```

```{r narrowing down crime rate data and joining with unemployment data}
# In general, I usually save over old objects while cleaning
# them or modifying them in some way. It may be a safer
# practice to name them something new every time, but because
# I'm working with a ton of data and in multiple Rmd and R
# script files, I tend to save over them.

custom2 <- custom2 %>%
  select(Year, PropertyCrimeRt, PersonCrmRt)

# The line above selects the columns out of custom2 that I
# need to join with the unemployment data I already have
# loaded in at the beginning of this Rmd.

# I suppose I could have further cleaned unemp for usage
# in unempcrime below by only keeping the Avg and Year
# columns. I didn't, because I may use all of the monthly
# values in unempcrime for another visualization later.
# I thought I would at least make a note to myself about
# this later.

unempcrime <- inner_join(unemp, custom2, by = "Year")

# This is an inner join that joins the data in unemp and
# custom together by year. Inner joins keep all data
# present in both tibbles, whereas right and left
# joins only keep some of the data in either of the
# tibbles. Look up tidyr and its cheatsheat if you're
# confused on how joins work and when you should use
# which join function.
```

```{r plotting property crime rate against yearly average unemployment rate}
unemppropcrime <- ggplot(unempcrime, aes(x = Avg, y = PropertyCrimeRt)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
    title = "Yearly Property Crime Rate and Yearly Average
    Unemployment Rate",

    # Note the title break here again.

    subtitle = "Inverse Relationship between Crime Rate and
    Unemployment Rate",

    # I also had to break the subtitle.

    caption = "Property crime rate is the number of property crimes reported per 1,000 people."
  ) +
  theme_minimal() +
  ylab("Property Crime Rate") +
  xlab("Yearly Average Unemployment Rate")

# I did try modifying the font size in my graphs, but it was
# even uglier than having the titles split as they are. this
# will have to do.
```

```{r}
coef1 <- lm(formula = PropertyCrimeRt ~ Avg, data = unempcrime)

table1 <- tidy(coef1)

table1[1, 1] <- "Intercept"

table1[2, 1] <- "Unemployment"

table1 <- table1 %>%
  mutate(estimate = round(estimate, digits = 3)) %>%
  mutate(std.error = round(std.error, digits = 3)) %>%
  mutate(statistic = round(statistic, digits = 3))

table2 <- table1 %>%
  gt() %>%
  tab_header("Coefficients: Property Crime Rate and Unemployment") %>%
  cols_label(term = "", estimate = "Estimate", std.error = "Standard Error", statistic = "Statistic", p.value = "P Value")
```

```{r}
# Running gtsave() for the first time prompted me to install the
# package webshot. I did that and loaded it with library(). Then
# I got a weird message about phantomjs. I ran the below code
# (commented out) and gtsave() then worked like how it should.

# webshot::install_phantomjs()

# You may or may not need to run the above line of code. Try running
# the line below by itself. If it returns an error that begins with
# "PhantomJS not found..." then run the above line of code and
# gtsave() should work.

table2 %>% gtsave("table2.png", zoom = 1)

# When I ran this in Shiny originally, it was huge. I used the
# zoom argument to make it more in line with the sizes of my
# ggplot graphs.

# I originally tried using the same method of saving my gt table as
# a PNG that I used with all my ggplot objects. Apparently png()
# doesn't work on gt objects. I googled how to save a gt table
# as an image and found gtsave, which I believe I have used before
# or seen used before in past problem sets.

# I was then able to copy and delete the spare PNG file like normal
# using fs.

file_copy(
  path = "table2.png",
  new_path = "pdx-probs/www/table2.png",
  overwrite = TRUE
)

file_delete(path = "table2.png")
```


```{r saving unemppropcrime as an image, include=FALSE}
png("unemppropcrime.png", width = 576, height = 576, res = 120)
unemppropcrime
dev.off()

file_copy(
  path = "unemppropcrime.png",
  new_path = "pdx-probs/www/unemppropcrime.png",
  overwrite = TRUE
)

file_delete(path = "unemppropcrime.png")
```

```{r plotting person crime rate against yearly average unemployment rate}
# This is the same thing as the above ggplot, but I changed which
# crime rate I was plotting.

unempperscrime <- ggplot(unempcrime, aes(x = Avg, y = PersonCrmRt)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
    title = "Yearly Person Crime Rate and Yearly Average
    Unemployment Rate",
    subtitle = "No Clear Relationship Between Person Crime Rate and
    Unemployment Rate",
    caption = "Property crime rate is the number of property crimes reported per 1,000 people."
  ) +
  theme_minimal() +
  ylab("Property Crime Rate") +
  xlab("Yearly Average Unemployment Rate")
```

```{r saving unempperscrime as an image, include=FALSE}
png("unempperscrime.png", width = 576, height = 576, res = 120)
unempperscrime
dev.off()

file_copy(
  path = "unempperscrime.png",
  new_path = "pdx-probs/www/unempperscrime.png",
  overwrite = TRUE
)

file_delete(path = "unempperscrime.png")
```

```{r}
unempplot
unemppropcrime
unempperscrime
```

